version: '2'

services:
  db:
    image: postgres
    volumes:
      - surveydata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    ports:
      - "8000:80"
    depends_on:
     - db

volumes:
  surveydata:
    external: true
