# Generated by Django 2.1.1 on 2018-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablespecification',
            name='campaign',
        ),
        migrations.AddField(
            model_name='surveycampaign',
            name='tables',
            field=models.ManyToManyField(to='core.TableSpecification'),
        ),
    ]
