# Generated by Django 2.1.1 on 2018-09-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180925_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycampaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
