# Generated by Django 2.1.1 on 2018-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_surveycampaign_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
