# Generated by Django 2.1.1 on 2018-09-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180927_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
